on: [push]

jobs:
  test:
    environment:
      name: test
    runs-on: ubuntu-latest
    env:
      FOOBAR: ${{ secrets.FOOBAR }}
    steps:
      - run: |
          printf 'Value of FOOBAR: "%s"\n' "$FOOBAR"
